# Generated by Django 2.2.3 on 2019-08-01 11:18

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.datetime_safe.datetime.now),
        ),
    ]
