language: python
python:
  - "3.6"
#  - "3.7"
services:
  - mysql
env:
  -DJANGO=2.2 DB=mysql
install: # => 5
  - pip install -r requirements.txt
before_script: # => 6
  - mysql -e 'create database test;' -u root
script: # => 7
  - python manage.py test
  - pylint --load-plugins pylint_django blog/
  - pylint --load-plugins pylint_django polls/
  - pylint --load-plugins pylint_django posts/