version: '3'

services:
  db:
    image: mysql:5.7
    ports:
      - '3308:3308'
    environment:
       MYSQL_DATABASE: 'django'
       MYSQL_USER: 'root'
       MYSQL_PASSWORD: 'root'
       MYSQL_ROOT_PASSWORD: 'root'
#    volumes:
#      - dbdata:/var/lib/mysql/
#      - ./mysql/my.cnf:/etc/mysql/my.cnf
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
#Volumes
#volumes:
#  dbdata:
#    driver: local